"""Step 9 — compare the runs and write the final report.

    uv run python scripts/09_report.py

Reads checkpoints/*/history.json and results/wer_*.json and produces
figures/09_scaling.png plus RESULTS.md.
"""

from __future__ import annotations

import json
from pathlib import Path

from whispr.plotting import ACCENT, ACCENT2, MUTED, plt, save, use_style

ROOT = Path(__file__).resolve().parent.parent
CHECKPOINTS = ROOT / "checkpoints"
RESULTS = ROOT / "results"

RUNS = [
    ("3.7h baseline", "run_3.7h", "wer_3.7h.json", ACCENT2),
    ("100h", "run_100h", "wer_100h.json", ACCENT),
]


def load_run(dirname: str, wer_name: str) -> dict | None:
    d = CHECKPOINTS / dirname
    hist_files = [d / "history_phase1.json", d / "history.json"]
    history: list[dict] = []
    for f in hist_files:
        if f.exists():
            history.extend(json.loads(f.read_text()))
    if not history:
        return None
    # Phase 1 + phase 2 may overlap at the resume point; keep the last per step.
    by_step = {h["step"]: h for h in sorted(history, key=lambda x: x["step"])}
    history = [by_step[k] for k in sorted(by_step)]

    wer = None
    wf = RESULTS / wer_name
    if wf.exists():
        wer = json.loads(wf.read_text())
    return {"history": history, "wer": wer}


def fig_scaling(runs: dict) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(11.5, 3.8))

    for label, dirname, _, color in RUNS:
        r = runs.get(label)
        if not r:
            continue
        h = r["history"]
        val = [(x["step"], x["val_loss"]) for x in h if "val_loss" in x]
        axes[0].plot([x["step"] for x in h], [x["train_loss"] for x in h],
                     color=color, lw=0.9, alpha=0.45)
        if val:
            axes[0].plot(*zip(*val), color=color, lw=1.8, label=f"{label} — val")
            best = min(val, key=lambda x: x[1])
            axes[0].plot([best[0]], [best[1]], "o", color=color, ms=6, mfc="white", mew=1.6)
            axes[0].annotate(f"{best[1]:.2f}", best, textcoords="offset points",
                             xytext=(6, 8), fontsize=7.5, color=color)

    axes[0].set_xlabel("step")
    axes[0].set_ylabel("cross-entropy")
    axes[0].set_title("Faint = train, solid = held-out val", loc="left")
    axes[0].legend(fontsize=7.5)
    axes[0].grid(True, lw=0.5)

    # WER vs hours of training audio, with reference points.
    hours, wers, labels = [], [], []
    for label, _, wer_name, color in RUNS:
        r = runs.get(label)
        if r and r["wer"]:
            held = next((x for x in r["wer"]["results"]
                         if x["label"].startswith("held-out")), None)
            if held:
                hours.append(r["wer"]["train_hours"])
                wers.append(held["wer"] * 100)
                labels.append(label)

    if hours:
        axes[1].plot(hours, wers, "o-", color=ACCENT, lw=1.8, ms=7)
        for h, w, lab in zip(hours, wers, labels):
            axes[1].annotate(f"{lab}: {w:.0f}%", (h, w), textcoords="offset points",
                             xytext=(0, 12), fontsize=7.5, color=ACCENT, ha="center")

    # Context: what other systems achieve, for honest framing.
    for h, w, lab, style in (
        (960, 5.0, "LibriSpeech SOTA\n960h + LM  ~5%", ":"),
        (680_000, 5.4, "whisper-tiny\n680,000h  ~5.4%", "--"),
    ):
        axes[1].plot([h], [w], "s", color=MUTED, ms=6)
        axes[1].annotate(lab, (h, w), textcoords="offset points", xytext=(0, 9),
                         fontsize=7, color=MUTED, ha="center", va="bottom")

    axes[1].set_xscale("log")
    axes[1].set_yscale("log")
    axes[1].set_xlabel("hours of training audio (log)")
    axes[1].set_ylabel("WER % on held-out speech (log)")
    axes[1].set_title("Where we sit on the curve", loc="left")
    axes[1].set_xlim(1.5, 3e6)
    axes[1].set_ylim(3, 400)
    axes[1].grid(True, lw=0.5, which="both")

    fig.suptitle("27x more data removes the overfitting U and cuts WER — but 100 h "
                 "is still nowhere near enough",
                 x=0.02, ha="left", weight="bold")
    fig.tight_layout()
    save(fig, "09_scaling.png")


def write_results_md(runs: dict) -> None:
    lines = [
        "# Results",
        "",
        "Generated by `scripts/09_report.py`. All validation is on **unseen",
        "speakers** — the 3.7 h run holds out 6 speakers from dev-clean, the 100 h",
        "run trains on train-clean-100 and validates on all of dev-clean",
        "(speaker-disjoint by corpus design).",
        "",
        "## Summary",
        "",
        "| Run | Train audio | Steps | Epochs | Best val loss | WER (unseen) | WER (seen) |",
        "|---|---|---|---|---|---|---|",
    ]
    for label, _, _, _ in RUNS:
        r = runs.get(label)
        if not r:
            continue
        val = [(x["step"], x["val_loss"]) for x in r["history"] if "val_loss" in x]
        best = min(val, key=lambda x: x[1]) if val else (0, float("nan"))
        w = r["wer"]
        if w:
            # Match on the leading word, not on "seen" — "seen)" is a substring
            # of "(unseen)", which silently made both columns the same number.
            held = next((x for x in w["results"] if x["label"].startswith("held-out")), {})
            seen = next((x for x in w["results"] if x["label"].startswith("training")), {})
            hours = w["train_hours"]
            # epochs = optimiser steps * batch size / training utterances
            utts = w.get("train_utts")
            bs = w.get("batch_size", 8)
            epochs = f"{best[0] * bs / utts:.1f}" if utts else "-"
            lines.append(
                f"| {label} | {hours:.1f} h | {best[0]:,} | ~{epochs} | "
                f"**{best[1]:.3f}** | **{held.get('wer', float('nan'))*100:.1f}%** | "
                f"{seen.get('wer', float('nan'))*100:.1f}% |"
            )
        else:
            lines.append(f"| {label} | — | {best[0]:,} | — | **{best[1]:.3f}** | not evaluated | — |")

    lines += [
        "",
        "## Reading these numbers",
        "",
        "WER above 100% is possible and means the model emits more words than the",
        "reference; insertions are unbounded, so WER is not a percentage of",
        "anything.",
        "",
        "For context, on read English speech:",
        "",
        "| System | Training audio | WER |",
        "|---|---|---|",
        "| **this repo, 3.7 h** | 3.7 h, ~6 epochs | **123%** |",
        "| **this repo, 100 h** | 100 h, ~5 epochs | **110%** |",
        "| Typical seq2seq, LibriSpeech-100 | 100 h, 50-100+ epochs | ~15-25% |",
        "| LibriSpeech SOTA | 960 h + language model | ~2-5% |",
        "| whisper-tiny (zero-shot) | 680,000 h | ~5-8% |",
        "",
        "The gap to row 3 is **epochs, not method**: our 100 h run did ~5 passes",
        "where those systems do 50-100+, and its validation loss was still falling",
        "when we stopped it. The gap to rows 4-5 is data volume.",
        "",
        "## What changed between the two runs",
        "",
        "The interesting result is not the WER, it is the *shape* of the failure.",
        "",
        "**3.7 h — a language model that ignores the audio.** Near-identical output",
        "regardless of input, and a textbook overfitting curve: validation bottomed at",
        "step 1,500 then climbed to 7.56 while training loss fell to 0.59.",
        "",
        "```",
        "REF  MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD",
        "HYP  THE HILLS WERE THE OTHER AND THE OTHER AS IF THE OTHERLY AND THE",
        "```",
        "",
        "**100 h — varied English with partial acoustic grounding.** Output now depends",
        "on the input, sentence openings are often right, and substitutions are",
        "acoustically plausible rather than arbitrary:",
        "",
        "```",
        "REF  HE WAS MOUNTED UPON A POWERFUL HORSE AND HAD ON A COAT OF MAIL",
        "HYP  HE WAS A TALL MAN OF A POPULAR STONE AND A LITTLE MORE THAN A MAN",
        "```",
        "",
        "\"HE WAS\" is correct and POWERFUL -> POPULAR is a phonetic confusion, not a",
        "guess. The alignment is forming; it has not finished forming.",
        "",
        "And the generalisation gap **inverted**: 27x more data took it from",
        "+8 points (memorising) to roughly zero. At 100 h this model is no longer",
        "overfitting — it is *underfitting*, which is a far better problem to have and",
        "says the next win comes from more epochs rather than more regularisation.",
        "",
        "See [`notes/08-decoding-and-wer.md`](notes/08-decoding-and-wer.md) and",
        "[`notes/09-what-next.md`](notes/09-what-next.md).",
        "",
    ]
    (ROOT / "RESULTS.md").write_text("\n".join(lines))
    print(f"  wrote {ROOT/'RESULTS.md'}")


if __name__ == "__main__":
    use_style()
    print("Step 9 — comparing the runs\n")
    runs = {}
    for label, dirname, wer_name, _ in RUNS:
        r = load_run(dirname, wer_name)
        if r:
            runs[label] = r
            val = [x["val_loss"] for x in r["history"] if "val_loss" in x]
            print(f"  {label:<16} {len(r['history']):>4} records, "
                  f"{len(val)} evals, best val {min(val):.4f}"
                  f"{'' if r['wer'] else '  (no WER yet)'}")
        else:
            print(f"  {label:<16} not found")

    fig_scaling(runs)
    write_results_md(runs)
